name: tvpost_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: '>=0.5.12 <2.0.0'
  progress_dialog: ^1.2.4
  async: ^2.4.2
  image_picker: ^0.6.7+11
  file_picker: ^2.0.6
  chewie: ^0.9.10
  video_player: '>=0.10.0 <2.0.0'
  webview_flutter: ^1.0.0
  url_launcher: ^5.7.10
  flutter_colorpicker: ^0.3.4
  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^3.2.2
  image_gallery_saver: ^1.6.6
  path_provider: ^1.6.11
  dio: ^3.0.9
  permission_handler: ^5.0.1
  fluttertoast: ^4.0.0
  share: ^0.6.5+4
  esys_flutter_share: ^1.0.2
  image: ^2.1.19
  network_image_to_byte: ^0.0.1
  liquid_pull_to_refresh: ^1.1.0
  hexcolor: ^1.0.6
  flutter_social_content_share: ^0.0.3
  fswitch: ^1.1.2
  lite_rolling_switch: ^0.1.1
  circular_profile_avatar: ^1.0.6
  store_redirect: ^1.0.2
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.3
  intl: ^0.16.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
     - family: tituloAxis
       fonts:
         - asset: fonts/axis.ttf 
  #         style: italic
     - family: textoMont
       fonts:
         - asset: fonts/Lato-Light.ttf
     - family: tvlapiz
       fonts:
         - asset: iconos/Tvlapiz.ttf  
     - family:  CustomIcons
       fonts:
       - asset: iconos/CustomIcons.ttf
     - family:  IconSoporte
       fonts:
       - asset: iconos/IconSoporte.ttf
     - family:  IconRRSS
       fonts:
       - asset: iconos/IconRRSS.ttf
     
       
      

  # To add assets to your application, add an assets section, like this:
  assets:
     - imagenes/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
