/// Flutter icons Tvlapiz
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tvlapiz
///      fonts:
///       - asset: fonts/Tvlapiz.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Tvlapiz {
  Tvlapiz._();

  static const _kFontFam = 'tvlapiz';
  static const String _kFontPkg = null;

  static const IconData lapiz =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
